services:
  app:
    container_name: calendar-api
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${PORT}:${PORT}
    networks:
      - api-network
    depends_on:
      - postgres
    environment:
      - PORT=${PORT}
  postgres:
    container_name: database
    build:
      dockerfile: ./database/Dockerfile
      context: .
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - api-network
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

networks:
  api-network:
    name: api-network
    driver: bridge